[package]
name = "house_simulator_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.1"

[profile.release]
lto = true

[profile.release-thin-lto]
inherits = "release"
lto = "thin"
